/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteNewEntityArgs } from "./DeleteNewEntityArgs";
import { NewEntityFindManyArgs } from "./NewEntityFindManyArgs";
import { NewEntityFindUniqueArgs } from "./NewEntityFindUniqueArgs";
import { NewEntity } from "./NewEntity";
import { NewEntityService } from "../newEntity.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => NewEntity)
export class NewEntityResolverBase {
  constructor(
    protected readonly service: NewEntityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "NewEntity",
    action: "read",
    possession: "any",
  })
  async _newEntitiesMeta(
    @graphql.Args() args: NewEntityFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [NewEntity])
  @nestAccessControl.UseRoles({
    resource: "NewEntity",
    action: "read",
    possession: "any",
  })
  async newEntities(
    @graphql.Args() args: NewEntityFindManyArgs
  ): Promise<NewEntity[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => NewEntity, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "NewEntity",
    action: "read",
    possession: "own",
  })
  async newEntity(
    @graphql.Args() args: NewEntityFindUniqueArgs
  ): Promise<NewEntity | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => NewEntity)
  @nestAccessControl.UseRoles({
    resource: "NewEntity",
    action: "delete",
    possession: "any",
  })
  async deleteNewEntity(
    @graphql.Args() args: DeleteNewEntityArgs
  ): Promise<NewEntity | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
